language: node_js
node_js:
  - "8"
  
sudo: required
services:
  - docker

before_install:
  - npm install -g node-gyp
  - docker build -t ddbogdanovich/angular_docker -f Dockerfile.dev .

sctipt:
   - docker run ddbogdanovich/angular_docker npm run test --watch=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "angApp"
  env: "Angapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-160876748667"
  bucket_path: "angApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"