language: node_js
node_js:
  - "8"
  
sudo: required
services:
  - docker

before_install:
  - docker build -t ddbogdanovich/angular_docker -f Dockerfile .

sctipt:
   - docker run ddbogdanovich/angular_docker npm run test --watch=false